server:
  port: 6789
  compression.enabled: true
  max-http-header-size: 20000

grpc:
  port: 6790

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  ## Data Source Properties
  datasource:
    url: jdbc:mysql://localhost:3306/classicmodels
    username: root
    password: trung9898
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
    database: mysql
  main:
    allow-bean-definition-overriding: true